### ISSUE TITLE
Listing files in root

### ISSUE THREAD

**Issue by kvannotten** [jackdoe/baxx#2]
I can't seem to list files in the root dir.

Ie: `curl https://baxx.dev/ls/TOKENHERE/` always returns "error: record not found", even when there's files there.

**Comment by jackdoe** [comment]
hmm strange, are you sure you are using the right token?

```
curl https://baxx.dev/ls/$BAXX_TOKEN/
/chunked: total size: 28319254 (0.0264GB)
1871739 Mon Apr  1 21:27:57 2019        /chunked/api.aa@v149*   08a8e2366900cb92061b7abfe815352164ae993745e01f7e8c0e39f65dcf354c
.....
sum total size: 28319254 (0.0264GB)
~/work % curl https://baxx.dev/ls/$BAXX_TOKEN 
404 page not found
%
````

there is issue however if you dont add / the route does not match

**Comment by jackdoe** [comment]
you can check your tokens with `curl -u your.email@example.com https://baxx.dev/protected/status` and confirm that you pasted the correct id

i saw a couple of alert for request with a token id that has 1 less symbol in it, so i guess that is the issue

**Comment by kvannotten** [comment]
yup, seems to be ok now! Thanks!
